name: Python application

on:
  push:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu:22.04
    steps:
      - name: Проверка наличия изменений
        uses: actions/checkout@v3

      - name: Установка пайтон
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Установка зависимостей
        run: pip install -r requirements.txt
